version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `data`
      - npm install
      - echo npm install completed on `data`
      - npm run build
      - echo npm run build completed on `data`
  post_build:
    commands:
      - echo Buil completed on `data`
      - ls -l ./dist/shop/

artifacts:
  files:
    - ./dist/shop/*
    - ./dist/shop/assets/*
    - appspec.yaml